### ISSUE TITLE
Add link to blog on GitHub homepage

### ISSUE THREAD

**Issue by slackline** [rdatatable-community/The-Raft#4]
Hi,

I'm thought it might be useful to add a link to the blog itself to the landing page here on GitHub.

To the right of the file/code listing there is the about section...

![image](https://github.com/rdatatable-community/The-Raft/assets/776695/61894645-a809-4991-900b-41ccbebcc778)

Under the settings icon you can enter a Website and if you own/have admin rights to the repo there should be a button to select "_This repositories GitHub Pagews_" or similar (not shown in the screenshot below I'm afraid). If its not shown then you can just enter `https://rdatatable-community.github.io/The-Raft/` as that is what is required.

![image](https://github.com/rdatatable-community/The-Raft/assets/776695/6ed8ebcc-4b8e-44d3-8377-051ff33f5ffa)

Once enabled the URL of the blog will be shown on the GitHub page under Actions.

**Comment by kbodwin** [comment]
Done, thank you for the suggestion! :)
