### ISSUE TITLE
white raft definition text unreadable due to white background

### ISSUE THREAD

**Issue by tdhock** [rdatatable-community/The-Raft#44]
![image](https://github.com/user-attachments/assets/8fb84ae0-264f-4c1d-b0c3-1e722fea7b35)
@kbodwin could the text color, or background, be changed please?
Does anyone else observe this problem or is it just me? (chromium browser, ubuntu)

**Comment by Anirban166** [comment]
> Does anyone else observe this problem or is it just me? (chromium browser, ubuntu)

I'm observing a light gray color (more precisely its `#cacccd` upon inspection) for the text (not white, but I agree that the contrast could be much better)

<img width="330" alt="image" src="https://github.com/user-attachments/assets/c8757eab-e034-4178-9def-4b2edd1d1c31">

(and in case you didn't highlight the text for it to be visible to show in this thread, I don't observe that orange background)

I'd suggest checking stylesheet overlaps (or styles conflicting with quarto-defined CSS rules), and the background should be tweakable in this section here:
https://github.com/rdatatable-community/The-Raft/blob/5ffff9cc22bcb540c7db4e32b73e4c3f24781251/index.qmd#L15

**Comment by kbodwin** [comment]
Fixed a while back and I forgot to close this, I forget which PR, thank you!
