### ISSUE TITLE
RSS feed not showing, perhaps switch to publishing action

### ISSUE THREAD

**Issue by slackline** [rdatatable-community/The-Raft#5]
#2 hasn't worked as expected. There is still no RSS feed shown in the top bar of the blog page.

![image](https://github.com/rdatatable-community/The-Raft/assets/776695/ec6fb7aa-66ee-474b-bb57-fff6fcf92791)

I think I know why though.

It looks like this Quarto blog is setup and built locally, updated files/posts are made locally, added to Git and then pushed. I think this is the case because...

+ There is not `.github/workflows/publish.yaml` [action](https://quarto.org/docs/publishing/github-pages.html#publish-action) that builds the site automatically on pushes to the `main` branch.
+ The `_site` and `_freeze`directories are present, the former certainly probably shouldn't be there according to the [Publishing | Github Pages - Ignoring Output](https://quarto.org/docs/publishing/github-pages.html#ignoring-output).

Switching to using the publishing action and removing `_site` would mean pushes to the `main` branch are published automatically rather than rendering/previewing locally, having to stage new files in git and then push them.

Its often wise to [protect your `main` branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches) by at the very least requiring a pull request. This means that new posts have to be made on a branch and a pull-request created to purge them as you can't then push from your local computer to GitHub, but that isn't necessarily a bad thing.

Happy to help with any aspects of this, I do it fairly regularly for work, just assign it to me and I'll knock up a PR.

**Comment by ns-rse** [comment]
The RSS feed button is there but it returns a [404](https://rdatatable-community.github.io/The-Raft/index.xml)

**Comment by tdhock** [comment]
@Anirban166 do you know anything about RSS? Can you please help get this working, so we can submit the raft to R-bloggers.com?

**Comment by tdhock** [comment]
here is the form for adding to r-bloggers https://www.r-bloggers.com/add-your-blog/

**Comment by Anirban166** [comment]
> @Anirban166 do you know anything about RSS? Can you please help get this working, so we can submit the raft to R-bloggers.com?

I don't. I'll look into it when I'm done with my current tasks.

**Comment by slackline** [comment]
I think the reason the RSS feed isn't working is because in addition to enabling the RSS icon in `_quartol.yaml` the `index.qmd` is missing the following [required lines](https://quarto.org/docs/websites/website-blog.html#rss-feed).

```yaml
listing:
  ...
  feed: true
```

Once that is added I suspect the RSS feed will work and a submission can then be made to R-bloggers.com.

Switching to GitHub actions to build the site when pushes are made to `main` using a [GitHub Action](https://quarto.org/docs/publishing/github-pages.html#github-action) probably should have been a separate issue, apologies.

**Comment by tdhock** [comment]
@slackline thanks for the info about the github action and rss feed, would #6 accomplish that?

**Comment by kbodwin** [comment]
These were both finished but I never closed the PR, sorry about that, and thanks again to @slackline for the suggestion and help!
