### ISSUE TITLE
still no bullet points in conclusion sections of duckdb/polars post

### ISSUE THREAD

**Issue by tdhock** [rdatatable-community/The-Raft#61]
hi @kbodwin after merging #53 I thought the bullet list would be visible but it is still not (asterisks in a big paragraph are visible instead)

![image](https://github.com/user-attachments/assets/7f4e4214-afaa-4553-8db6-56c28cad9c4e)

![image](https://github.com/user-attachments/assets/c16bf975-00c8-4562-be55-666cfa342fc6)

I thought adding a newline would fix that issue... did you re-build that page after merging the pr? If not then rebuilding is probably the fix. If so then how do we fix?

**Comment by kbodwin** [comment]
Fixed by #66

**Comment by tdhock** [comment]
great thanks!
