### ISSUE TITLE
Contrast issues in the theme

### ISSUE THREAD

**Issue by eliocamp** [rdatatable-community/The-Raft#8]
I was adding an article to the blog and realised that the colours used in the theme have some contrast issues. 

The title and tags have [very low contrast](https://webaim.org/resources/contrastchecker/?fcolor=6E8387&bcolor=073642)

![image](https://github.com/rdatatable-community/The-Raft/assets/8617595/8da07f00-e19e-4285-a3c8-7aa4517b83d8)

And similarly, code blocks have a very dark background that makes it almost impossible to see some elements of the code: 

![image](https://github.com/rdatatable-community/The-Raft/assets/8617595/9a6c5ac4-1b56-4532-82a7-e47cc5b4fd00)

**Comment by kbodwin** [comment]
Eeesh, you're right, that's not a good consequence of the theme colors chosen!  Let me figure out how to make that better (and post your awesome blog post!) tomorrow.
